### PR TITLE
Add option to limit max resource size

### PR DESCRIPTION
**Pull request by vbanos**
Add hidden option ``--max-resource-size`` which indicates the max file size of
a target resource in bytes. If the size is over the limit, an exception is
raised.

### CODE REVIEW

**Comment by nlevitt** [comment]
Thanks @vbanos, this is good functionality for warcprox to support. 

- as you mentioned on slack, needs a test
- let's advertise the feature (remove `argparse.SUPPRESS`)
- ideally rather than throw an exception, it should close the connection, then continue processing normally, writing a warc record with `WARC-Truncated: length` (but please check with Kenji if this will cause problems for wayback)
- I think you can use `prox_rec_res.len` instead of keeping a `size` variable

Are you also planning to implement a time limit?

**Comment by vbanos** [comment]
Yes, I'm planning to implement a time limit on a different PR.

**Comment by vbanos** [comment]
I forgot to mention in my latest commit we no longer throw an exception but we just log a msg when truncation happens and continue processing.
Also the ``argparse.SUPPRESS`` is removed.

**Comment by nlevitt** [comment]
This is causing a test to fail but I have a fix which I will commit after merging.

**Pull request merged**
